idf_component_register(
    SRCS
        "main.c"
        "wifi_ap.c"
        "mavlink_router.c"
        "camera_stream.c"
        "vision_pipeline.c"
        "marker_detector.c"
        "optical_flow.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver
        esp_wifi
        esp_event
        nvs_flash
        esp_http_server
        esp32-camera
        lwip
        esp_timer
        soc
        esp_hw_support
)
